"""empty message

Revision ID: 79c80b05ba17
Revises: a35ad1195bd6
Create Date: 2021-06-09 13:15:36.299682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c80b05ba17'
down_revision = 'a35ad1195bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('edad', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'edad')
    # ### end Alembic commands ###
