"""empty message

Revision ID: a35ad1195bd6
Revises: a513a58f4bb6
Create Date: 2021-06-02 12:57:49.444303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35ad1195bd6'
down_revision = 'a513a58f4bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('direccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'direccion')
    # ### end Alembic commands ###
